image: node

install:
  - npm install

build_script:
  - npm run build
  - npm test

artifacts:
  - path: dist
    name: output

deploy:
  provider: GitHub
  auth_token:
    secure: RffCgR1apxcJX/0Ti1xqlSvT2I5nRcQvsEbZe8wy0+A05jfgu9GjiMojgndd0lVJ
  on:
    branch: main
